services:
  pg_protocol_rewards:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: protocol_rewards
      POSTGRES_PASSWORD: protocol_rewards
      POSTGRES_DB: protocol_rewards
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - protocol-rewards-network

  delegation_rewards:
    image: ghcr.io/tez-capital/protocol-rewards:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
    environment:
      LISTEN: 127.0.0.1:8080
      PRIVATE_LISTEN: 127.0.0.1:8081
    volumes:
      - ./config.hjson:/config.hjson:ro
    depends_on:
      - pg_delegation_rewards
      - node
    networks:
      - protocol-rewards-network
    logging:
      driver: json-file
      options:
        max-size: '200k' # Maximum file size
        max-file: '10' # Maximum number of files

  node:
    image: ghcr.io/tez-capital/xtz.node:latest
    volumes:
      - ./node:/ascend:rw
    networks:
      - protocol-rewards-network
    stop_grace_period: 5m00s
    logging:
      driver: json-file
      options:
        max-size: '200k' # Maximum file size
        max-file: '10' # Maximum number of files

networks:
  protocol-rewards-network:
    driver: bridge
