services:
  pg_delegation_rewards:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: protocol_rewards
      POSTGRES_PASSWORD: protocol_rewards
      POSTGRES_DB: protocol_rewards
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - betanet-delegation-rewards-network

  delegation_rewards:
    image: ghcr.io/mavryk-network/protocol-rewards:latest
    restart: always
    ports:
      - "127.0.0.1:8082:8080"
      - "127.0.0.1:8083:8081"
    environment:
      LISTEN: 0.0.0.0:8080
      PRIVATE_LISTEN: 0.0.0.0:8081
    volumes:
      - ./config.hjson:/config.hjson:ro
    depends_on:
      - pg_delegation_rewards
    networks:
      - betanet-delegation-rewards-network
    logging:
      driver: json-file
      options:
        max-size: '200k' # Maximum file size
        max-file: '10' # Maximum number of files

networks:
  betanet-delegation-rewards-network:
    driver: bridge