name: release

on:
  release:
    types: [created]

jobs:       
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: protocol-rewards container
        uses: docker/build-push-action@v4
        with:
          file: ./containers/protocol-rewards/Containerfile
          platforms: linux/amd64
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/tez-capital/protocol-rewards:latest,ghcr.io/tez-capital/protocol-rewards:${{github.ref_name}}
          push: true
          provenance: false
